version: '3.2'

services:
  web:
    build: .
    environment:
      DJANGO_SECRET_KEY: 'secret_key'
      DJANGO_ALLOWED_HOSTS: '*'
      DJANGO_INTERNAL_IPS: '127.0.0.1,::1,172.19.0.1'
      DJANGO_DEBUG: 'True'
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    ports:
      - '8000:8000'
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: 'corbis'
      POSTGRES_PASSWORD: '!Q2w3e4r%T'
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pg-data: