# Generated by Django 2.2.2 on 2019-06-21 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price')),
                ('stock', models.PositiveSmallIntegerField(default=0, verbose_name='Stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
            },
        ),
    ]
